# Criando o primeiro workflow do GitHub Actions para dizer "Hello World!" e "See ya!" quando houver um push para a branch master.

name: "Hello World"

on: 
  push:
    branches: [ master ]

  jobs:
    say-hello:
      runs-on: ubuntu-latest
      steps:
        - name: "Say Hello"
          run: echo "Hello World!"
        - name: "Say See ya"
          run: echo "See ya!"